// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjX0JiBetSERtzlUPUqkFFtBxUMRz3mQA',
    appId: '1:318774755159:web:82c335ab8ff8ebbc094812',
    messagingSenderId: '318774755159',
    projectId: 'ecommerce-clot',
    authDomain: 'ecommerce-clot.firebaseapp.com',
    storageBucket: 'ecommerce-clot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBNs64WOTb69TbgJOxyPyY2bPe36JzOIw',
    appId: '1:318774755159:android:6705f0c20b3935c4094812',
    messagingSenderId: '318774755159',
    projectId: 'ecommerce-clot',
    storageBucket: 'ecommerce-clot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPkmoeVo6U8vA3sN1p9PC9XdZ92tis1yM',
    appId: '1:318774755159:ios:75410e9355afc417094812',
    messagingSenderId: '318774755159',
    projectId: 'ecommerce-clot',
    storageBucket: 'ecommerce-clot.appspot.com',
    iosBundleId: 'com.example.ecommerceClot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPkmoeVo6U8vA3sN1p9PC9XdZ92tis1yM',
    appId: '1:318774755159:ios:75410e9355afc417094812',
    messagingSenderId: '318774755159',
    projectId: 'ecommerce-clot',
    storageBucket: 'ecommerce-clot.appspot.com',
    iosBundleId: 'com.example.ecommerceClot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjX0JiBetSERtzlUPUqkFFtBxUMRz3mQA',
    appId: '1:318774755159:web:894b8e26c59432c9094812',
    messagingSenderId: '318774755159',
    projectId: 'ecommerce-clot',
    authDomain: 'ecommerce-clot.firebaseapp.com',
    storageBucket: 'ecommerce-clot.appspot.com',
  );
}
